# spring.application.name=Reelcry
# server.port=${PORT:8080}
# spring.thymeleaf.cache=false
# spring.data.redis.repositories.enabled=false
# spring.cache.type=redis
# spring.data.redis.host=${REDIS_HOST:localhost}
# spring.data.redis.port=${REDIS_PORT:6379}
# spring.data.redis.password=${REDIS_PASSWORD:}
spring.application.name=Reelcry
server.port=${PORT:8080}
spring.thymeleaf.cache=true
spring.cache.type=simple