# spring.application.name=Reelcry
# server.port=${PORT:8080}
# spring.thymeleaf.cache=false
# spring.data.redis.repositories.enabled=false
# spring.cache.type=redis
# spring.data.redis.host=${REDIS_HOST:localhost}
# spring.data.redis.port=${REDIS_PORT:6379}
# spring.data.redis.password=${REDIS_PASSWORD:}
spring.application.name=Reelcry
server.port=${PORT:8080}
spring.thymeleaf.cache=true
spring.cache.type=simple
app.auth.username1=${APP_AUTH_USERNAME1:admin}
app.auth.password1=${APP_AUTH_PASSWORD1:123}
app.auth.username2=${APP_AUTH_USERNAME2:family}
app.auth.password2=${APP_AUTH_PASSWORD2:123}